### PR TITLE
Private networking support.

### PR DESCRIPTION
**Pull request by kfletche**

### CODE REVIEW

**Comment by yadutaf** [comment]
That's a really great addition! Something I've wanted to do for long bug never got the time to. Thanks :)

If I get your design proposition right:
- by default, the machine gets the public network only
- if ``--ovh-private-network`` is provided, the machine gets both networks

I like this design, lots of users / tools are not ready for "private-only" systems.

For private networks, I'm not sure names really make sense for most of us. What I use on a daily basis are rather vlan numbers. As vlan must be unique in the private network section, my suggestion would be to accept a vlan ID as argument to ``--ovh-private-network``. Does it seem feasible to you ?

**Comment by kfletche** [comment]
That's the idea. For us private networking was definitely something we needed.

Probably missing something here but is there a reason the API call doesn't bring up dhcp addresses on private networks on new machine instances? I can do it after the fact but wondering if there might be a better place for it?

**Comment by yadutaf** [comment]
I've taken some time to play around with your PR. I love it. Thanks !

**Comment by yadutaf** [comment]
Out of curiosity, how do you configure the private interface once the machine is UP ?

**Pull request merged**
