### PR TITLE
Be more precise about what is ovh-project

### PR DESCRIPTION
**Pull request by jfroche**
We want to make sure that user provides the project id (ex: 6705e3c6a1694bb181b8421649e7b24e)

### CODE REVIEW

**Comment by yadutaf** [comment]
Actually, name OR id is fine. As IDs are harder to find in the admin panel, I tend to favor the "name" expression as opposed to "id". If the name does not work, this is a bug.

**Comment by yadutaf** [comment]
While merging your previous PR, I tested with

```
docker-machine create -d ovh --ovh-project "docker-machine" test
```

It works as expected (read: with your fix) when selecting a project by name.

**Comment by jfroche** [comment]
API describe a project description but not a project name (https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D#GET). You are right, we can provide both id or description/name. I have adapted the README and the commit msg.

**Comment by yadutaf** [comment]
Thanks!

**Pull request merged**
