### PR TITLE
Improve package naming

### PR DESCRIPTION
**Pull request by y8**
Improved package naming to close the #21

### CODE REVIEW

**Comment by yadutaf** [comment]
This looks good. I just need to test it in details before merging.

**Comment by yadutaf** [comment]
Tested and merged. Thanks !

**Comment by tuxity** [comment]
@yadutaf Could you upload new binaries names in github release please ? :) It's a needed if you want to install the driver in Rancher

**Comment by tuxity** [comment]
@yadutaf Merci :)

**Comment by yadutaf** [comment]
:)

**Pull request merged**
